_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/coco/novel_try/model_reset_remove.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 20
#     FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
DATASETS:
  TRAIN: ('coco_trainval_novel_5shot',)
  TEST: ('coco_test_novel',)
SOLVER:
#   IMS_PER_BATCH: 16
#   BASE_LR: 0.01
#   STEPS: (10000,)
#   MAX_ITER: 5000
#   CHECKPOINT_PERIOD: 500
#   WARMUP_ITERS: 0
  
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (72000,)
  MAX_ITER: 80000
  CHECKPOINT_PERIOD: 4000
  WARMUP_ITERS: 10
OUTPUT_DIR: "checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_ft_novel_5shot_unfreeze_lastfews_80000"